// import '@/styles/globals.css';

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import { Providers } from '@/providers';
// import SideBar from '@/components/ui/SideBar';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang='en'>
//       <body className='w-screen'>
//         <div className='flex items-center'>
//           <SideBar />
//           <Providers>{children}</Providers>
//         </div>
//       </body>
//     </html>
//   );
// }

import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/providers';
import SideBar from '@/components/ui/SideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className=''>
        <div className='flex'>
          <SideBar />
          <main className='flex-1'>
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
